### ISSUE TITLE
Please include Skladnik

### ISSUE THREAD

**Issue by yarons** [ivan-hc/KDE-games-suite-appimage#1]
It's a Sokoban clone.
Thanks.

**Comment by ivan-hc** [comment]
Should be included in the next build, about 10-15 minutes after this comment. Just started a workflow run in github actions

**Comment by ivan-hc** [comment]
Tested, you should get an error about mirring templates, but this happens in several KDE games, don't really affects gameplay.

**Comment by yarons** [comment]
Thank you so much :)
