### ISSUE TITLE
Include translations

### ISSUE THREAD

**Issue by yarons** [ivan-hc/KDE-games-suite-appimage#2]
I was wondering if there's a chance to include the localizations for the games and specify them with `--language` argument and ISO639 code
for example:
`KDE-GAMES-SUITE_24.02-2-archimage3.2-x86_64.AppImage picmi --language he`

Thank you :)

**Comment by ivan-hc** [comment]
Hi, is this a feature of the real packages from repositories? I.E., is this `--language` an official option of games in KDE (from repositories)? If so, it should already work.

**Comment by yarons** [comment]
No, it's not, in KDE I need to install the translations separately and modify the LC_ALL/LC_MESSAGE to make it work that way.

**Comment by ivan-hc** [comment]
@yarons I normally don't add nothing to what the Arch Linux (container) provides, I only bundle the app as is

**Comment by yarons** [comment]
Yes, apparently adding KDE Localizations in Arch linux is a little complicated, I'll try to see if there are other options, thanks,

**Comment by yarons** [comment]
If there was a way to simply add translations using AUR or any other way related to package management it would be solved somehow but I can't find anything like that so I guess we can close this one for now, thank you.
