### ISSUE TITLE
Palapeli is not loading properly

### ISSUE THREAD

**Issue by yarons** [ivan-hc/KDE-games-suite-appimage#4]
Palapeli is a Puzzle game, there is no board loaded on startup and no board could be configured of created, the game is basically stuck on a spinner.

**Comment by ivan-hc** [comment]
I'm investigating

**Comment by ivan-hc** [comment]
I'm considering bundle the AppImage with all files (excluded gcc and some others), +200MB compared to this release.

I'm doing tests, but still have issues with both palapeli and kajongg

**Comment by yarons** [comment]
I see, I'll try to fork and see if I can help.

**Comment by ivan-hc** [comment]
I've just updated the script

https://github.com/ivan-hc/KDE-games-suite-appimage/commit/9ccad9a518f2a357d8abc6c6cb88ab77f36cb7ac

the final AppImage will be about 670 MB

**Comment by ivan-hc** [comment]
however, it's still unable to launche correwctly the affected apps of your two issues

I think there is a missing package I don't know

**Comment by ivan-hc** [comment]
I can't figure out on why it can't read and load the pictures, I get always the same error:
```
failed to create drawable
qt.gui.imageio: libpng warning: known incorrect sRGB profile
qt.gui.imageio: libpng warning: profile matches sRGB but writing iCCP instead
```

EDIT: if this is related to libEGL and to HW accelleration in general, I can't do much, since JuNest does not support it

**Comment by yarons** [comment]
That sucks, thank you for all your wonderful work, is there a bug open in JuNest?

**Comment by ivan-hc** [comment]
> That sucks, thank you for all your wonderful work, is there a bug open in JuNest?

I'm stuck in my Archimage project with my searches https://github.com/ivan-hc/ArchImage/issues/20

I've tried to involve more people on the main repository of JuNest, but the developer does not seem to be interested.

JuNest should work well if you install drivers for Arch in JuNest, while you use it normally. Its not ment to be a solution to build AppImages as I do in almost all my repositories.

**Comment by ivan-hc** [comment]
I've tested palapeli in normal junest and worked, so I've tried to include everything without removals in the AppImage... and didn't worked. Its strange.

**Comment by yarons** [comment]
Seems like you've discovered a bug in Palapeli or Junest or both :)

**Comment by ivan-hc** [comment]
I think that its related to a system daemon or something

**Comment by ivan-hc** [comment]
@yarons I want to keep you updated, for now nothing has changed, apart this strange behaviour:
- launching palapeli using junest from the extacted AppImage works correctly
- launching it from the AppRun core script doesn't work

https://github.com/ivan-hc/KDE-games-suite-appimage/assets/88724353/65677f8d-697b-4759-9a87-11b4e5c9c961

tested with all $BINDS mounted too. Nothing changes.

Same directory, different behaviours.

**Comment by ivan-hc** [comment]
I've found the issue, in the AppRun the command must call "$@", not "$1" "$@"

**Comment by Player100** [comment]
> however, it's still unable to launche correwctly the affected apps of your two issues
> 
> I think there is a missing package I don't know
>
i try to run the game in terminal and message returned:
_palapeli: error while loading shared libraries: libvorbisfile.so.3: cannot open shared object file: No such file or directory_

**Comment by ivan-hc** [comment]
> > however, it's still unable to launche correwctly the affected apps of your two issues
> > I think there is a missing package I don't know
> 
> i try to run the game in terminal and message returned: _palapeli: error while loading shared libraries: libvorbisfile.so.3: cannot open shared object file: No such file or directory_

next build will have the fix
